name: Enviar para Quaxly

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do GitHub
        uses: actions/checkout@v4

      - name: Preparar cache do npm
        run: |
          mkdir -p .npm
          touch .npm/.gitkeep
          echo "cache=.npm" > .npmrc

      - name: Enviar package.json
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.QUAXLY_USER }}
          server: ${{ secrets.QUAXLY_HOST }}
          port: ${{ secrets.QUAXLY_PORT }}
          password: ${{ secrets.QUAXLY_PASSWORD }}
          local_path: './package.json'
          remote_path: '/'
          sftp_only: true

      - name: Enviar npmrc
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.QUAXLY_USER }}
          server: ${{ secrets.QUAXLY_HOST }}
          port: ${{ secrets.QUAXLY_PORT }}
          password: ${{ secrets.QUAXLY_PASSWORD }}
          local_path: './.npmrc'
          remote_path: '/'
          sftp_only: true

      - name: Enviar cache npm
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.QUAXLY_USER }}
          server: ${{ secrets.QUAXLY_HOST }}
          port: ${{ secrets.QUAXLY_PORT }}
          password: ${{ secrets.QUAXLY_PASSWORD }}
          local_path: './.npm/*'
          remote_path: '/.npm'
          sftp_only: true

      - name: Enviar src
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.QUAXLY_USER }}
          server: ${{ secrets.QUAXLY_HOST }}
          port: ${{ secrets.QUAXLY_PORT }}
          password: ${{ secrets.QUAXLY_PASSWORD }}
          local_path: './src/*'
          remote_path: '/src'
          sftp_only: true
